_target_: src.training.experiment_runner.TabICLTaskwiseExperiment
name: tabicl_taskwise
wandb_enabled: ${wandb.enabled}
device: ${device}

n_estimators: 8
validation_metric: rmse
crps_alphas: null
model_params:
  n_jobs: 1
