# @package _global_
defaults:
  - override /model: np
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: random
  - override /hydra/launcher: joblib
  - _self_

# Hydra Configuration
hydra:
  mode: MULTIRUN
  # REQUIRED: Change both output paths for your system.
  run:
    dir: /userdata/${oc.env:USER}/hydra_outputs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /userdata/${oc.env:USER}/hydra_outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}

  sweeper:
    sampler:
      _target_: optuna.samplers.RandomSampler
      seed: ${data.experiment.seed}
    
    n_trials: 32
    params:
      # Neural Process Parameters
      model.params.dropout: interval(0.0,0.2)
      model.train_params.learning_rate: tag(log, interval(1e-5,1e-3))

  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 1

  job:
    chdir: true